one-click script for Azure
Taraxa-project/taraxa-ops pull request #13
Opened 2021-07-02 22:27 UTC by silentrvnning

Script to instantiate a Taraxa node running on Azure cloud

2021-07-05 08:37 UTC, rattrap commented
Thanks for this @silentrvnning.

I tested it and it only seems to work on debian-based Linux distros.
Ca we make this universal and make sure it also works on MacOS?

2021-07-07 17:16 UTC, silentrvnning commented
Yep, modified the script and it should work on MacOS now. Added also support for the general install script, which should work for more distros. Added also some error checking for various commands.

2021-07-08 08:43 UTC, rattrap approved these changes

2021-07-08 08:43 UTC, rattrap commented on scripts/one-click-Azure.sh
> +az vm open-port --resource-group ${AZ_GROUP_NAME} --name ${AZ_APP_SERVICE_NAME} --port 7777,8777,10022 > /dev/null
Ports should be: `3000,7777,8777,10002`

2021-07-08 08:45 UTC, rattrap requested changes
Looks good! Just change the ports I mentioned and I will merge it!

2021-07-08 19:29 UTC, rattrap approved these changes

2021-07-08 19:30 UTC, merged