feat: add one click script on Vultr.
Taraxa-project/taraxa-ops pull request #9
Opened 2021-06-28 14:08 UTC by jiangydev

2021-06-28 18:57 UTC, rattrap commented
Looks good overall. If you can make it work on MacOS, we'll give you the tokens.

2021-06-28 20:06 UTC, rattrap requested changes

2021-06-29 02:58 UTC, jiangydev commented on scripts/one-click-Vultr.sh
> +if [ "$RETURN" != 0 ]; then
Added a judgment, hope to be effective

2021-06-29 08:40 UTC, rattrap approved these changes
Works great!
Check out the comment on the documentation PR and after you fix that, submit the two PR urls here: https://community.taraxa.io/submit/48

2021-06-29 08:47 UTC, merged